#!/usr/bin/env python3

import requests
from lxml import html
from datetime import date

userName = 'brunosabenca'
targetDate = date.today()

def getGitHubUserContributeCountByDate(userName, targetDate):
  r = requests.get('https://github.com/users/' + userName + '/contributions')
  h = html.fromstring(r.content)
  rect = h.cssselect('rect.day[data-date="' + str(targetDate) + '"]')

  if len(rect) > 0:
    count = rect[0].get('data-count')
  else:
    count = '0'

  return count

count = getGitHubUserContributeCountByDate(userName, targetDate)

print('  ' + count + ' ')

if count == '0':
  exit(33)
